"""Curated translations of working downloader pages.

Only a slug with complete page copy is published. Adding a locale to the
registry is deliberately separate from adding a language to the sitemap.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class LocalizedTool:
    heading: str
    intro: str
    how: str
    formats: str
    limits: str
    question: str
    answer: str


LANGUAGE_UI = {
    "es": {
        "name": "Español",
        "home_title": "Descargador y convertidor de vídeos | SaveFromNet",
        "home_heading": "Descarga y convierte medios públicos",
        "home_intro": "Pega el enlace directo de un vídeo, Reel, Short, foto o audio que tengas permiso para guardar. Comprueba los formatos disponibles antes de preparar el archivo.",
        "nav_tools": "Herramientas",
        "nav_how": "Cómo funciona",
        "nav_rights": "Uso responsable",
        "url_label": "Enlace público del contenido",
        "url_placeholder": "Pega aquí un enlace público",
        "paste": "Pegar",
        "download": "Analizar enlace",
        "rights": "Descarga solo contenido propio o para el que tengas permiso. No accedemos a publicaciones privadas ni evitamos restricciones.",
        "formats_title": "Opciones reales para cada enlace",
        "formats_home": "El analizador identifica la plataforma y muestra únicamente los archivos y calidades que puede preparar para ese contenido. Una resolución ausente no se puede crear cambiando la dirección.",
        "how_title": "Cómo usar el descargador",
        "how_home": "Copia el enlace de una publicación individual, pégalo arriba y analiza el resultado. Elige un formato que aparezca en la lista; la preparación se realiza en segundo plano y el archivo temporal se guarda desde tu navegador.",
        "limits_title": "Cuando el contenido no está disponible",
        "limits_home": "Las publicaciones eliminadas, privadas, en directo, limitadas por región o que exigen iniciar sesión pueden fallar. SaveFromNet no evita DRM, muros de pago ni controles de acceso.",
        "platforms_title": "Plataformas y herramientas",
        "related_title": "Herramientas relacionadas",
        "faq_title": "Preguntas frecuentes",
        "faq_home_question": "¿Puedo elegir cualquier calidad?",
        "faq_home_answer": "No. Cada fuente devuelve sus propios formatos. Solo mostramos las opciones que el servicio puede preparar para ese enlace.",
        "faq_availability_question": "¿Por qué no aparece el archivo que busco?",
        "faq_availability_answer": "Puede faltar en la fuente o requerir acceso privado, inicio de sesión o una región concreta. Prueba un enlace directo a una publicación pública.",
        "history_title": "Descargas recientes de este navegador",
        "history_view": "Ver historial",
        "footer": "Descarga únicamente contenido que tengas derecho a usar.",
        "english": "English",
        "french": "Français",
    },
    "fr": {
        "name": "Français",
        "home_title": "Téléchargeur et convertisseur vidéo | SaveFromNet",
        "home_heading": "Téléchargez et convertissez des médias publics",
        "home_intro": "Collez le lien direct d'une vidéo, d'un Reel, d'un Short, d'une photo ou d'un audio que vous avez le droit d'enregistrer. Vérifiez les formats disponibles avant de préparer le fichier.",
        "nav_tools": "Outils",
        "nav_how": "Mode d'emploi",
        "nav_rights": "Utilisation responsable",
        "url_label": "Lien public du contenu",
        "url_placeholder": "Collez un lien public ici",
        "paste": "Coller",
        "download": "Analyser le lien",
        "rights": "Téléchargez uniquement vos contenus ou ceux pour lesquels vous avez une autorisation. Nous n'accédons pas aux publications privées et ne contournons aucune restriction.",
        "formats_title": "Les formats réellement disponibles",
        "formats_home": "L'analyseur reconnaît la plateforme et n'affiche que les fichiers et qualités qu'il peut préparer pour ce contenu. Modifier l'URL ne crée pas une résolution absente.",
        "how_title": "Comment utiliser le téléchargeur",
        "how_home": "Copiez le lien d'une publication précise, collez-le ci-dessus et analysez le résultat. Choisissez un format proposé : la préparation se fait en arrière-plan et le fichier temporaire s'enregistre depuis votre navigateur.",
        "limits_title": "Quand un contenu reste inaccessible",
        "limits_home": "Les publications supprimées, privées, en direct, limitées à une région ou nécessitant une connexion peuvent échouer. SaveFromNet ne contourne ni DRM, ni paywalls, ni contrôle d'accès.",
        "platforms_title": "Plateformes et outils",
        "related_title": "Outils associés",
        "faq_title": "Questions fréquentes",
        "faq_home_question": "Puis-je choisir n'importe quelle qualité ?",
        "faq_home_answer": "Non. Chaque source propose ses propres formats. Seules les options que le service peut préparer pour ce lien sont affichées.",
        "faq_availability_question": "Pourquoi le fichier voulu n'apparaît-il pas ?",
        "faq_availability_answer": "Il peut manquer à la source ou nécessiter un accès privé, une connexion ou une région précise. Essayez le lien direct d'une publication publique.",
        "history_title": "Téléchargements récents de ce navigateur",
        "history_view": "Voir l'historique",
        "footer": "Téléchargez uniquement les contenus que vous avez le droit d'utiliser.",
        "english": "English",
        "spanish": "Español",
    },
}


LOCALIZED_TOOLS = {
    "es": {
        "universal-video-downloader": LocalizedTool(
            "Descargador y convertidor universal",
            "Un solo campo para enlaces públicos de ocho plataformas compatibles.",
            "Pega el enlace de una publicación concreta. El detector comprueba el dominio y la ruta y envía ese contenido al extractor correspondiente; una página de búsqueda no identifica un archivo.",
            "El resultado puede contener vídeo, audio o imágenes según la fuente. Elige una opción que aparezca tras el análisis, nunca una calidad supuesta.",
            "Cada plataforma impone sus propios límites. Un enlace privado, eliminado o que requiera iniciar sesión no se puede procesar.",
            "¿Admite cualquier sitio web?",
            "No. Se aceptan enlaces públicos compatibles de YouTube, Instagram, TikTok, Facebook, Pinterest, Reddit, Threads y Dailymotion.",
        ),
        "youtube-downloader": LocalizedTool(
            "Descargador y convertidor de YouTube",
            "Compara vídeo y audio de un vídeo o Short público de YouTube.",
            "Usa un enlace directo youtube.com/watch, youtube.com/shorts o youtu.be de un solo contenido. Tras analizarlo podrás comparar las opciones de vídeo y sonido disponibles.",
            "Pueden aparecer MP4, WebM, audio original o una conversión MP3 cuando exista una pista sonora accesible. La lista depende de esa publicación.",
            "Las listas de reproducción, los alquileres, los directos y los vídeos privados no forman parte de este flujo público.",
            "¿El convertidor garantiza 4K o MP3?",
            "No. Solo ofrece las combinaciones que el extractor encuentra y puede preparar dentro del límite de tamaño.",
        ),
        "youtube-video-downloader": LocalizedTool(
            "Descargador de vídeos de YouTube",
            "Guarda un vídeo público con una resolución que realmente esté disponible.",
            "Copia el enlace de la página watch?v= o su versión youtu.be. Analiza ese único vídeo y consulta el tipo de archivo, la altura y la estimación de tamaño antes de elegir.",
            "Una opción de alta resolución puede necesitar unir vídeo y audio compatibles. MP4 y WebM no son intercambiables solo por cambiar la extensión.",
            "Si el vídeo está eliminado, restringido o bloqueado para accesos anónimos, no aparecerá ninguna descarga.",
            "¿Todos los vídeos ofrecen 1080p?",
            "No. La resolución depende de las pistas accesibles para el vídeo concreto y del límite de procesamiento.",
        ),
        "youtube-shorts-downloader": LocalizedTool(
            "Descargador de YouTube Shorts",
            "Analiza un Short público y guarda una opción de vídeo disponible.",
            "Abre el Short individual y copia su URL youtube.com/shorts/ con el identificador. Un feed de Shorts o un canal no señala un archivo específico.",
            "Los vídeos verticales pueden exponer diferentes tamaños y contenedores. El resultado muestra únicamente las variantes devueltas para ese Short.",
            "Un Short privado, eliminado, en directo o bloqueado por YouTube no se puede obtener mediante un cambio de URL.",
            "¿Puedo guardar solo el sonido?",
            "Si existe audio accesible, abre el convertidor de YouTube a MP3 de la sección de herramientas relacionadas.",
        ),
        "youtube-to-mp3": LocalizedTool(
            "Convertidor de YouTube a MP3",
            "Convierte a MP3 el audio accesible de un vídeo o Short público.",
            "Pega un enlace directo de YouTube y espera al análisis. Selecciona la opción MP3 que aparezca; el servidor extrae el audio y lo convierte antes de crear un archivo temporal.",
            "MP3 es una conversión del sonido original, no un archivo que YouTube entregue necesariamente. Una tasa de bits mayor no restaura calidad perdida.",
            "Los vídeos sin audio, las listas, las publicaciones privadas y los contenidos que exigen iniciar sesión no producen un MP3 aquí.",
            "¿Siempre está disponible MP3 a 320 kbps?",
            "No. Elige solo las opciones mostradas para ese enlace; no prometemos una tasa de bits fija.",
        ),
        "youtube-to-mp4": LocalizedTool(
            "Convertidor de YouTube a MP4",
            "Encuentra las resoluciones MP4 que se pueden preparar para un vídeo público.",
            "Pega el enlace de un vídeo o Short. El resultado se centra en las opciones MP4 devueltas para ese contenido, en vez de mostrar una lista fija de resoluciones.",
            "Algunos vídeos separan imagen y sonido; el servidor solo ofrece un MP4 terminado cuando puede combinar pistas compatibles.",
            "Si la fuente devuelve únicamente WebM o no ofrece cierta altura, no se puede forzar MP4 cambiando el nombre del archivo.",
            "¿Cambiar WebM a .mp4 convierte el vídeo?",
            "No. Cambiar la extensión no modifica el códec ni crea una opción MP4 que no exista.",
        ),
        "instagram-downloader": LocalizedTool(
            "Descargador de Instagram",
            "Analiza fotos y vídeos de publicaciones o Reels públicos.",
            "Copia la URL directa instagram.com/p/ o instagram.com/reel/ de una publicación. El resultado puede contener una foto, un vídeo o varios elementos de un carrusel.",
            "Las imágenes conservan el formato expuesto por la fuente; los vídeos aparecen solo si la publicación ofrece un archivo accesible.",
            "Instagram puede solicitar una cuenta incluso en ciertas publicaciones visibles como públicas. No accedemos a perfiles privados.",
            "¿Se puede pegar el enlace de un perfil?",
            "Esta página se centra en publicaciones individuales. Un perfil puede requerir inicio de sesión y no equivale a un solo archivo.",
        ),
        "instagram-reels-downloader": LocalizedTool(
            "Descargador de Reels de Instagram",
            "Consulta si un Reel público ofrece un vídeo accesible.",
            "Usa la URL directa instagram.com/reel/ del Reel que puedes guardar. Analízala para ver si el extractor devuelve un archivo de vídeo para esa publicación.",
            "Normalmente se muestra la opción MP4 de origen cuando está disponible; no se inventan alturas adicionales.",
            "Los Reels eliminados, privados o sujetos a inicio de sesión pueden no devolver ningún formato.",
            "¿Sirve un enlace al feed de Reels?",
            "No. Copia el enlace de un Reel individual, no el de una página de exploración o un perfil.",
        ),
        "instagram-photo-downloader": LocalizedTool(
            "Descargador de fotos de Instagram",
            "Encuentra las imágenes originales de una publicación pública.",
            "Pega un enlace instagram.com/p/ que contenga fotografías. Si es un carrusel, revisa cada elemento accesible que devuelve el análisis.",
            "Una imagen puede aparecer como JPEG, PNG o WebP según lo que exponga Instagram. Un vídeo sin foto no ofrece una descarga fotográfica.",
            "Las publicaciones privadas o que exigen una sesión activa no se recuperan aquí.",
            "¿Convierte las fotos a otra resolución?",
            "Esta herramienta muestra los archivos expuestos por la fuente. Para convertir una imagen propia después, usa las herramientas de imagen del sitio.",
        ),
        "tiktok-downloader": LocalizedTool(
            "Descargador de TikTok",
            "Analiza un vídeo o publicación fotográfica pública de TikTok.",
            "Copia el enlace de un vídeo /@usuario/video/ID, una publicación /photo/ID o un enlace corto vm.tiktok.com que apunte a una pieza concreta.",
            "El analizador muestra los vídeos, fotos o pistas de audio que TikTok permita consultar para ese enlace. Las calidades no se fijan por adelantado.",
            "TikTok puede bloquear peticiones de centros de datos o retirar una publicación; no se evita el inicio de sesión.",
            "¿Se puede descargar el sonido de un vídeo?",
            "Si existe audio accesible, abre el convertidor de TikTok a MP3 para ver la opción correspondiente.",
        ),
        "tiktok-to-mp3": LocalizedTool(
            "Convertidor de TikTok a MP3",
            "Prepara un MP3 a partir del sonido accesible de un vídeo público.",
            "Pega la URL directa /@usuario/video/ID o un enlace corto al mismo vídeo. Elige MP3 solo cuando el análisis encuentre una pista sonora.",
            "El servidor convierte la pista disponible; un clip silencioso no puede convertirse en música o voz.",
            "Una historia caducada, un vídeo eliminado o un enlace bloqueado por TikTok no tendrá audio descargable.",
            "¿MP3 mejora el sonido del vídeo?",
            "No. La conversión cambia el formato, pero no recupera detalle que falte en el audio original.",
        ),
        "facebook-video-downloader": LocalizedTool(
            "Descargador de vídeos de Facebook",
            "Busca formatos de un vídeo o Reel público de Facebook.",
            "Pega una URL facebook.com/watch?v=, /videos/, /reel/ o fb.watch que identifique una publicación individual.",
            "La lista refleja los archivos que la fuente devuelve para ese vídeo; una resolución que no aparece no se puede solicitar manualmente.",
            "Los vídeos limitados a amigos, las páginas que exigen inicio de sesión y las publicaciones eliminadas quedan fuera.",
            "¿Puedo usar un enlace a un grupo privado?",
            "No. El servicio solo consulta contenido públicamente accesible sin iniciar sesión.",
        ),
        "pinterest-video-downloader": LocalizedTool(
            "Descargador de vídeos, imágenes y GIF de Pinterest",
            "Comprueba el archivo original de un Pin público.",
            "Copia la URL pinterest.com/pin/ID o su enlace corto pin.it. El contenido puede ser una imagen, un GIF o un vídeo.",
            "Se ofrece el elemento que el Pin expone realmente. Un Pin que remite a un sitio externo puede no alojar ningún archivo descargable en Pinterest.",
            "Los tableros completos y los Pins privados no identifican un único archivo público.",
            "¿Todos los Pins contienen vídeo?",
            "No. Muchos contienen solo una imagen o enlazan a una página externa; el resultado indica el tipo real.",
        ),
        "reddit-video-downloader": LocalizedTool(
            "Descargador de vídeos de Reddit",
            "Guarda un vídeo de una publicación pública, con sonido cuando exista.",
            "Usa el enlace permanente reddit.com/r/comunidad/comments/ID/ o un enlace corto redd.it/ID de una sola publicación.",
            "Reddit puede separar imagen y sonido. Cuando ambas pistas son accesibles y compatibles, el servidor las une en el archivo final.",
            "Los posts eliminados, privados, en cuarentena o marcados para adultos pueden impedir el acceso anónimo.",
            "¿Todos los vídeos de Reddit tienen sonido?",
            "No. Si la fuente no ofrece una pista sonora utilizable, el servicio no puede inventarla.",
        ),
        "threads-video-downloader": LocalizedTool(
            "Descargador de vídeos de Threads",
            "Comprueba si una publicación pública de Threads expone un vídeo.",
            "Pega el enlace directo threads.com/@usuario/post/ID. El analizador revisa los metadatos públicos de esa publicación individual.",
            "Si Threads publica un archivo MP4 accesible, se ofrece esa fuente. Es posible que no haya duración, tamaño o varias resoluciones.",
            "Los posts privados, sin metadatos de vídeo o que requieran iniciar sesión no dan lugar a un archivo.",
            "¿Por qué solo aparece una calidad?",
            "Threads puede exponer un único vídeo público; el servicio no crea variantes que la fuente no facilita.",
        ),
        "dailymotion-video-downloader": LocalizedTool(
            "Descargador de vídeos de Dailymotion",
            "Elige una calidad devuelta para un vídeo público concreto.",
            "Pega un enlace dailymotion.com/video/ID o dai.ly/ID. Analiza la publicación antes de escoger entre las alturas disponibles.",
            "El resultado puede incluir MP4 o WebM según las pistas accesibles. El tamaño estimado solo aparece cuando hay datos suficientes.",
            "Los canales, listas, vídeos privados y contenidos bloqueados por región no son enlaces a un archivo público utilizable.",
            "¿Puedo forzar una calidad superior?",
            "No. Solo se ofrecen las alturas devueltas para ese vídeo y compatibles con el límite de procesamiento.",
        ),
    },
    "fr": {
        "universal-video-downloader": LocalizedTool(
            "Téléchargeur et convertisseur universel",
            "Un seul champ pour les liens publics de huit plateformes compatibles.",
            "Collez le lien d'une publication précise. Le détecteur vérifie le domaine et le chemin avant de transmettre ce contenu à l'extracteur adapté ; une page de recherche ne désigne pas un fichier.",
            "Le résultat peut contenir de la vidéo, de l'audio ou des images selon la source. Choisissez une option affichée après l'analyse, jamais une qualité supposée.",
            "Chaque plateforme a ses propres limites. Un lien privé, supprimé ou nécessitant une connexion ne peut pas être traité.",
            "Tous les sites web sont-ils acceptés ?",
            "Non. L'outil accepte les liens publics compatibles de YouTube, Instagram, TikTok, Facebook, Pinterest, Reddit, Threads et Dailymotion.",
        ),
        "youtube-downloader": LocalizedTool(
            "Téléchargeur et convertisseur YouTube",
            "Comparez la vidéo et l'audio d'une vidéo ou d'un Short YouTube public.",
            "Utilisez le lien direct youtube.com/watch, youtube.com/shorts ou youtu.be d'un seul contenu. L'analyse permet ensuite de comparer les choix de vidéo et de son disponibles.",
            "MP4, WebM, audio d'origine ou conversion MP3 peuvent apparaître lorsqu'une piste sonore accessible existe. La liste dépend de cette publication.",
            "Les playlists, locations, directs et vidéos privées ne font pas partie de ce parcours public.",
            "Le convertisseur garantit-il la 4K ou le MP3 ?",
            "Non. Il propose seulement les combinaisons trouvées par l'extracteur et préparables dans la limite de taille.",
        ),
        "youtube-video-downloader": LocalizedTool(
            "Téléchargeur de vidéos YouTube",
            "Enregistrez une vidéo publique dans une résolution réellement disponible.",
            "Copiez le lien watch?v= ou sa version youtu.be. Analysez cette seule vidéo et vérifiez le type de fichier, la hauteur et l'estimation de taille avant de choisir.",
            "Une haute résolution peut nécessiter la fusion de pistes vidéo et audio compatibles. MP4 et WebM ne deviennent pas interchangeables en renommant le fichier.",
            "Une vidéo supprimée, restreinte ou bloquée pour les visiteurs anonymes ne donnera aucun fichier.",
            "Toutes les vidéos proposent-elles le 1080p ?",
            "Non. La résolution dépend des pistes accessibles pour cette vidéo et de la limite de traitement.",
        ),
        "youtube-shorts-downloader": LocalizedTool(
            "Téléchargeur de YouTube Shorts",
            "Analysez un Short public et enregistrez une vidéo proposée.",
            "Ouvrez le Short précis et copiez son URL youtube.com/shorts/ avec son identifiant. Un fil de Shorts ou une chaîne ne désigne pas un fichier unique.",
            "Les vidéos verticales peuvent avoir plusieurs tailles et conteneurs. Le résultat ne montre que les variantes renvoyées pour ce Short.",
            "Un Short privé, supprimé, en direct ou bloqué par YouTube ne devient pas accessible en modifiant l'URL.",
            "Puis-je enregistrer uniquement le son ?",
            "Si l'audio est accessible, ouvrez le convertisseur YouTube vers MP3 dans les outils associés.",
        ),
        "youtube-to-mp3": LocalizedTool(
            "Convertisseur YouTube en MP3",
            "Convertissez en MP3 l'audio accessible d'une vidéo ou d'un Short public.",
            "Collez un lien YouTube direct et attendez l'analyse. Sélectionnez l'option MP3 proposée : le serveur extrait puis convertit le son avant de créer un fichier temporaire.",
            "Le MP3 est une conversion de la piste d'origine, pas nécessairement un fichier fourni par YouTube. Un débit plus élevé ne restaure pas les détails perdus.",
            "Les vidéos muettes, playlists, publications privées ou nécessitant une connexion ne produisent pas de MP3 ici.",
            "Le MP3 à 320 kb/s est-il toujours proposé ?",
            "Non. Choisissez uniquement les options affichées pour ce lien ; aucun débit fixe n'est promis.",
        ),
        "youtube-to-mp4": LocalizedTool(
            "Convertisseur YouTube en MP4",
            "Trouvez les résolutions MP4 préparables pour une vidéo publique.",
            "Collez le lien d'une vidéo ou d'un Short. Le résultat se concentre sur les options MP4 de ce contenu au lieu d'afficher une liste fixe de résolutions.",
            "Certaines vidéos séparent image et son ; le serveur propose un MP4 final uniquement s'il peut associer des pistes compatibles.",
            "Si la source ne renvoie que du WebM ou omet une hauteur, renommer le fichier ne permet pas de forcer le MP4.",
            "Renommer un WebM en .mp4 suffit-il ?",
            "Non. L'extension ne modifie pas le codec et ne crée pas une option MP4 absente de la source.",
        ),
        "instagram-downloader": LocalizedTool(
            "Téléchargeur Instagram",
            "Analysez les photos et vidéos de publications ou Reels publics.",
            "Copiez l'URL directe instagram.com/p/ ou instagram.com/reel/ d'une publication. Le résultat peut contenir une photo, une vidéo ou plusieurs éléments d'un carrousel.",
            "Les images gardent le format exposé par la source ; une vidéo apparaît seulement si la publication fournit un fichier accessible.",
            "Instagram peut demander une connexion même pour certaines publications visibles publiquement. Les comptes privés sont exclus.",
            "Puis-je coller l'adresse d'un profil ?",
            "Cette page traite surtout les publications individuelles. Un profil peut nécessiter une connexion et ne correspond pas à un seul fichier.",
        ),
        "instagram-reels-downloader": LocalizedTool(
            "Téléchargeur de Reels Instagram",
            "Vérifiez si un Reel public fournit une vidéo accessible.",
            "Utilisez l'URL instagram.com/reel/ du Reel que vous pouvez enregistrer. Analysez-la pour voir si l'extracteur renvoie un fichier vidéo.",
            "Le MP4 d'origine est proposé lorsqu'il est accessible ; aucune résolution supplémentaire n'est inventée.",
            "Un Reel supprimé, privé ou soumis à une connexion peut ne renvoyer aucun format.",
            "Un lien vers le fil des Reels suffit-il ?",
            "Non. Copiez le lien d'un Reel précis, pas celui d'une page de découverte ou d'un profil.",
        ),
        "instagram-photo-downloader": LocalizedTool(
            "Téléchargeur de photos Instagram",
            "Trouvez les images d'origine d'une publication publique.",
            "Collez le lien instagram.com/p/ d'une publication contenant des photos. Pour un carrousel, examinez chaque élément accessible renvoyé par l'analyse.",
            "Une image peut être en JPEG, PNG ou WebP selon la source. Une publication uniquement vidéo ne donne pas de photo téléchargeable.",
            "Les publications privées ou nécessitant une session active ne sont pas récupérées.",
            "L'outil crée-t-il d'autres résolutions ?",
            "Il affiche les fichiers fournis par la source. Pour convertir ensuite votre propre image, utilisez les outils d'image du site.",
        ),
        "tiktok-downloader": LocalizedTool(
            "Téléchargeur TikTok",
            "Analysez une vidéo ou une publication photo TikTok publique.",
            "Copiez le lien d'une vidéo /@utilisateur/video/ID, d'une publication /photo/ID ou un lien court vm.tiktok.com vers un contenu précis.",
            "L'analyseur montre les vidéos, photos ou pistes audio que TikTok laisse consulter pour ce lien. Les qualités ne sont pas prédéfinies.",
            "TikTok peut bloquer les requêtes de centres de données ou supprimer une publication ; aucune connexion n'est contournée.",
            "Puis-je extraire le son d'une vidéo ?",
            "Si l'audio est accessible, ouvrez le convertisseur TikTok en MP3 pour voir l'option correspondante.",
        ),
        "tiktok-to-mp3": LocalizedTool(
            "Convertisseur TikTok en MP3",
            "Préparez un MP3 à partir du son accessible d'une vidéo publique.",
            "Collez l'URL directe /@utilisateur/video/ID ou un lien court vers cette vidéo. Choisissez MP3 uniquement si l'analyse trouve une piste sonore.",
            "Le serveur convertit la piste disponible ; une vidéo muette ne peut pas devenir de la musique ou de la parole.",
            "Une Story expirée, une vidéo supprimée ou un lien bloqué par TikTok n'a pas d'audio récupérable.",
            "Le MP3 améliore-t-il le son ?",
            "Non. La conversion change le format, mais ne restaure pas les détails absents de l'audio d'origine.",
        ),
        "facebook-video-downloader": LocalizedTool(
            "Téléchargeur de vidéos Facebook",
            "Cherchez les formats d'une vidéo ou d'un Reel Facebook public.",
            "Collez une URL facebook.com/watch?v=, /videos/, /reel/ ou fb.watch identifiant une publication précise.",
            "La liste reflète les fichiers renvoyés pour cette vidéo ; une résolution absente ne peut pas être demandée manuellement.",
            "Les vidéos réservées aux amis, les pages imposant une connexion et les publications supprimées sont exclues.",
            "Un lien de groupe privé fonctionne-t-il ?",
            "Non. Le service ne consulte que les contenus publics accessibles sans connexion.",
        ),
        "pinterest-video-downloader": LocalizedTool(
            "Téléchargeur de vidéos, images et GIF Pinterest",
            "Vérifiez le fichier d'origine d'une épingle publique.",
            "Copiez l'URL pinterest.com/pin/ID ou son lien court pin.it. Le contenu peut être une image, un GIF ou une vidéo.",
            "L'outil propose l'élément réellement exposé par l'épingle. Un lien vers un site externe peut ne contenir aucun fichier hébergé par Pinterest.",
            "Les tableaux entiers et les épingles privées ne désignent pas un fichier public unique.",
            "Toutes les épingles contiennent-elles une vidéo ?",
            "Non. Beaucoup ne comportent qu'une image ou mènent à un autre site ; le résultat indique le type réel.",
        ),
        "reddit-video-downloader": LocalizedTool(
            "Téléchargeur de vidéos Reddit",
            "Enregistrez une vidéo de publication publique, avec le son s'il existe.",
            "Utilisez le permalien reddit.com/r/communauté/comments/ID/ ou un lien court redd.it/ID d'une seule publication.",
            "Reddit peut séparer image et son. Lorsque les deux pistes sont accessibles et compatibles, le serveur les réunit dans le fichier final.",
            "Les posts supprimés, privés, en quarantaine ou réservés aux adultes peuvent bloquer l'accès anonyme.",
            "Toutes les vidéos Reddit ont-elles du son ?",
            "Non. Si la source ne fournit aucune piste sonore utilisable, le service ne peut pas en inventer.",
        ),
        "threads-video-downloader": LocalizedTool(
            "Téléchargeur de vidéos Threads",
            "Vérifiez si une publication Threads publique expose une vidéo.",
            "Collez le lien direct threads.com/@utilisateur/post/ID. L'analyseur consulte les métadonnées publiques de cette publication précise.",
            "Si Threads publie un MP4 accessible, ce fichier est proposé. La durée, la taille ou plusieurs résolutions peuvent manquer.",
            "Les posts privés, sans métadonnées vidéo ou nécessitant une connexion ne fournissent aucun fichier.",
            "Pourquoi n'y a-t-il qu'une seule qualité ?",
            "Threads peut n'exposer qu'une vidéo publique ; le service ne crée pas de variantes absentes de la source.",
        ),
        "dailymotion-video-downloader": LocalizedTool(
            "Téléchargeur de vidéos Dailymotion",
            "Choisissez une qualité renvoyée pour une vidéo publique précise.",
            "Collez un lien dailymotion.com/video/ID ou dai.ly/ID. Analysez la publication avant de choisir une hauteur disponible.",
            "Le résultat peut inclure du MP4 ou du WebM selon les pistes accessibles. Une estimation de taille n'apparaît que si les données suffisent.",
            "Les chaînes, playlists, vidéos privées et contenus bloqués par région ne fournissent pas de fichier public utilisable.",
            "Puis-je forcer une meilleure qualité ?",
            "Non. Seules les hauteurs renvoyées pour cette vidéo et compatibles avec la limite de traitement sont proposées.",
        ),
    },
}

PUBLISHED_SLUGS = tuple(LOCALIZED_TOOLS["es"])
assert set(PUBLISHED_SLUGS) == set(LOCALIZED_TOOLS["fr"])


def alternates(base_url, slug=None):
    """Return reciprocal absolute URLs only for published translations."""
    if slug is not None and slug not in PUBLISHED_SLUGS:
        return ()
    suffix = f"/{slug}" if slug else ""
    english = base_url + (suffix or "/")
    return (
        ("en", english),
        ("es", base_url + "/es" + suffix),
        ("fr", base_url + "/fr" + suffix),
        ("x-default", english),
    )
